import "../public/styles/globals.css";
import "../public/styles/font.css";
import { ReactNode } from "react";
import { Metadata } from "next";
import QueryProvider from "@/api/query-provider";
import { Toaster } from "@/components/base/Toaster";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
  modal,
}: {
  children: ReactNode;
  modal: ReactNode;
  showSideBar?: boolean;
}) {
  return (
    <html lang="fr">
      <head>
        <link rel="manifest" href="/manifest.json" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preload"
          href="/fonts/Gilroy-Regular.woff2"
          as="font"
          type="font/woff2"
          crossOrigin="anonymous"
        />
        <link
          rel="preload"
          href="/fonts/Gilroy-Bold.woff2"
          as="font"
          type="font/woff2"
          crossOrigin="anonymous"
        />
        <link
          rel="preload"
          href="/fonts/Gilroy-Medium.woff2"
          as="font"
          type="font/woff2"
          crossOrigin="anonymous"
        />
      </head>

      <body>
        <QueryProvider>
          {children}
          {modal}
        </QueryProvider>
        <Toaster />
      </body>
    </html>
  );
}
